version: '3.9'
services:
  web: 
    image: arm32v7/nginx
    ports:
    - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
    - NGINX_HOST=kuhakuzero.ddns.net
    - NGINX_PORT=80
  db:
    image: mysql
    ports: 
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demo